const resolveRoot=(r=document)=>typeof r==='string'?document.querySelector(r):r;
const $=(s,r=document)=>resolveRoot(r)?.querySelector(s)??null;
const $$=(s,r=document)=>[...(resolveRoot(r)?.querySelectorAll(s)??[])];
const STORE='marathonLiveOpsV1';
const seed={
  users:[
    {id:'admin',password:'admin123',role:'admin',name:'Project Admin'},
    {id:'ops',password:'ops123',role:'ops',name:'Rahul S.',department:'Race Course',zone:'Zone 03'},
    {id:'client',password:'client123',role:'client',name:'Client User'}
  ],
  project:{name:'Tata Steel World 25K Kolkata',eventDay:'Event Day - 02',readiness:78,lastUpdate:'04:47 AM'},
  departments:[
    {name:'Venue',progress:88,status:'On Track'},{name:'Race Course',progress:68,status:'Working'},
    {name:'Hydration',progress:74,status:'Working'},{name:'Medical',progress:91,status:'On Track'},
    {name:'Security',progress:82,status:'On Track'},{name:'Logistics',progress:63,status:'Attention'},
    {name:'Expo',progress:100,status:'Completed'},{name:'Branding',progress:79,status:'Working'}
  ],
  tasks:[
    {id:'RC-118',name:'KM 12 Directional Signage',phase:'Race Course',department:'Race Course',zone:'Zone 03',assignedTo:'ops',priority:'Critical',status:'Not Started',deadline:'04:45 AM',progress:0,clientVisibility:'Status + Approved Proof',instruction:'Install directional board facing runner flow. Confirm alignment and safety.',proofMin:3,verification:true,proofs:[],remark:'',issue:'',verified:false,fields:[
      {label:'Current Status',type:'dropdown',required:true,opsEdit:true,client:'Status',options:['Not Started','Just Started','Working','Unable to Start','Blocked','Delayed','Finished']},
      {label:'% Complete',type:'number',required:true,opsEdit:true,client:'Yes'},
      {label:'Specific Location',type:'text',required:true,opsEdit:true,client:'No'},
      {label:'Issue / Delay',type:'dropdown',required:true,opsEdit:true,client:'No',options:['No','Material Not Reached','Manpower Shortage','Vehicle Delay','Permission Issue','Safety Issue','Other']},
      {label:'Update Remark',type:'remark',required:true,opsEdit:true,client:'No'}
    ]},
    {id:'RC-119',name:'Barricade Check Z3',phase:'Race Course',department:'Race Course',zone:'Zone 03',assignedTo:'ops',priority:'High',status:'Working',deadline:'05:00 AM',progress:55,clientVisibility:'Status Only',instruction:'Check barricade continuity and runner safety.',proofMin:2,verification:true,proofs:[],remark:'',issue:'',verified:false,fields:[]},
    {id:'VN-201',name:'Finish Gate Branding',phase:'Venue',department:'Venue',zone:'Finish',assignedTo:'ops',priority:'High',status:'Finished',deadline:'04:10 AM',progress:100,clientVisibility:'Status + Approved Proof',instruction:'Final branding alignment check.',proofMin:2,verification:true,proofs:[],remark:'Completed and aligned.',issue:'',verified:false,fields:[]},
    {id:'HY-044',name:'Hydration Station H6',phase:'Race Course',department:'Hydration',zone:'KM 15',assignedTo:'ops',priority:'Medium',status:'Finished',deadline:'04:25 AM',progress:100,clientVisibility:'Status + Approved Proof',instruction:'Verify water, cups and volunteer readiness.',proofMin:1,verification:true,proofs:[],remark:'Ready.',issue:'',verified:true,fields:[]}
  ],
  team:[
    {name:'Rahul S.',userId:'ops',role:'Supervisor',department:'Race Course',zone:'Zone 03',access:'Assigned Only',status:'Active'},
    {name:'Priya M.',userId:'priya',role:'Coordinator',department:'Venue',zone:'Finish',access:'Department',status:'Active'},
    {name:'Amit K.',userId:'amit',role:'Lead',department:'Logistics',zone:'All',access:'Department',status:'Active'},
    {name:'Neha R.',userId:'neha',role:'Verifier',department:'Admin Ops',zone:'All',access:'Proof Only',status:'Active'}
  ],
  messages:[
    {thread:'RC-118',from:'ops',to:'admin',text:'Directional board has not reached the location.',time:'04:11 AM'},
    {thread:'RC-118',from:'admin',to:'ops',text:'Vehicle 04 is approaching. ETA 12 minutes.',time:'04:13 AM'},
    {thread:'client-artwork',from:'admin',to:'client',text:'Please review the revised artwork uploaded for approval.',time:'10:32 AM'},
    {thread:'client-artwork',from:'client',to:'admin',text:'Looks good. Please proceed with this version.',time:'10:41 AM'}
  ],
  approvals:[
    {id:'AP-1',title:'Start Gate Artwork',type:'Approve artwork',status:'Pending',note:'Please approve the final start gate artwork for production.'},
    {id:'AP-2',title:'Sponsor Logo Pack',type:'Upload file',status:'Pending',note:'Please provide the latest sponsor logo pack.'},
    {id:'AP-3',title:'Finish Branding',type:'Approval',status:'Approved',note:'Approved.'}
  ],
  issues:[
    {id:'IS-1',task:'RC-118',title:'Material not reached',severity:'High',status:'Open',time:'04:11 AM'},
    {id:'IS-2',task:'LG-08',title:'Water vehicle arrival delayed',severity:'Medium',status:'Open',time:'04:12 AM'}
  ],
  clientRules:{overall:true,departments:true,approvedProof:true,internalRemarks:false,vendorContacts:false,unverifiedIssues:false}
};
let state=JSON.parse(localStorage.getItem(STORE)||'null')||structuredClone(seed);
let session={role:null,user:null,page:null,selectedTask:null};
let unsubscribeCloud=()=>{};
const save=()=>{
  localStorage.setItem(STORE,JSON.stringify(state));
  if(window.LiveOpsCloud?.isConfigured()){
    const sync=window.LiveOpsResilience?.safeSave ? window.LiveOpsResilience.safeSave(state,session.role) : window.LiveOpsCloud.saveState(state,session.role);
    Promise.resolve(sync).then(r=>{if(r?.queued) toast('Saved offline — will sync automatically.');}).catch(err=>{console.error(err);toast('Cloud sync issue — local copy kept safely.');});
  }
};
const toast=(m)=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)};
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusClass=s=>/blocked|critical|rework/i.test(s)?'red':/delay|pending|attention|working/i.test(s)?'amber':/finish|complete|verified|active|track/i.test(s)?'green':'blue';

// public actions
$$('[data-open-login]').forEach(b=>b.addEventListener('click',()=>openLogin(b.dataset.openLogin)));
$('#closeLogin').onclick=()=>$('#loginModal').classList.add('hidden');
$('#loginModal').addEventListener('click',e=>{if(e.target===$('#loginModal'))$('#loginModal').classList.add('hidden')});
$('#contactForm').addEventListener('submit',async e=>{
  e.preventDefault();
  const form=Object.fromEntries(new FormData(e.target));
  try{
    if(window.LiveOpsCloud?.isConfigured()) await window.LiveOpsCloud.submitEnquiry(form);
    toast(window.LiveOpsCloud?.isConfigured()?'Enquiry sent successfully.':'Enquiry recorded for this demo.');
    e.target.reset();
  }catch(err){console.error(err);toast('Could not send enquiry. Please try again.');}
});
function openLogin(role){
  const cfg={ops:['OPS ACCESS','Your ground. Your tasks. Your updates.','Authorised operations personnel only.','ops / ops123'],client:['CLIENT ACCESS','Welcome to Marathon LiveOps','Secure access to your live project updates.','client / client123'],admin:['ADMIN ACCESS','Command the entire operation.','Configuration, verification and visibility control.','admin / admin123']}[role];
  $('#loginRole').value=role; $('#loginAccess').textContent=cfg[0];$('#loginTitle').textContent=cfg[1];$('#loginHelp').textContent=cfg[2];
  const cloudMode=!!window.LiveOpsCloud?.isConfigured();
  $('#demoCredentials').classList.toggle('hidden',cloudMode);
  $('#demoCredentials').innerHTML=cloudMode?'':`Demo login: <b>${cfg[3]}</b>`;
  $('#loginCard').className='login-modal '+role;$('#loginModal').classList.remove('hidden');
  $('#loginUser').value=cloudMode?'':role;
  $('#loginPassword').value=cloudMode?'':(role==='admin'?'admin123':role==='ops'?'ops123':'client123');
}
$('#loginForm').addEventListener('submit',async e=>{
  e.preventDefault();
  const role=$('#loginRole').value,u=$('#loginUser').value.trim(),p=$('#loginPassword').value;
  try{
    if(window.LiveOpsCloud?.isConfigured()){
      const auth=await window.LiveOpsCloud.signIn(u,p);
      if(!auth?.profile || !auth?.membership) throw new Error('Profile or project membership not found.');
      if(auth.membership.role!==role) throw new Error(`This account has ${auth.membership.role} access, not ${role} access.`);
      const cloudState=await window.LiveOpsCloud.loadState(role);
      if(cloudState){ state=cloudState; localStorage.setItem(STORE,JSON.stringify(state)); }
      else if(role!=='client'){ await window.LiveOpsCloud.saveState(state,role); }
      launch({id:auth.profile.liveops_user_id||u,role:auth.membership.role,name:auth.profile.name||u,department:auth.membership.department||'',zone:auth.membership.zone||''});
      unsubscribeCloud();
      unsubscribeCloud=window.LiveOpsCloud.subscribe(role,newState=>{state=newState;localStorage.setItem(STORE,JSON.stringify(state));if(session.page)navigate(session.page);toast('Live project update received.');});
      return;
    }
    const user=state.users.find(x=>x.id===u&&x.password===p&&x.role===role);
    if(!user)return toast('Incorrect User ID or password.');
    launch(user);
  }catch(err){console.error('LOGIN ERROR:',err);toast(err?.message||'Login failed.');}
});
$('#logoutBtn').onclick=async()=>{unsubscribeCloud();unsubscribeCloud=()=>{};if(window.LiveOpsCloud?.isConfigured())await window.LiveOpsCloud.signOut();session={role:null,user:null,page:null,selectedTask:null};$('#appShell').classList.add('hidden');$('#publicSite').classList.remove('hidden');$('#publicNav').classList.remove('hidden');$('.footer').classList.remove('hidden');window.scrollTo(0,0)};
function launch(user){session.user=user;session.role=user.role;$('#loginModal').classList.add('hidden');$('#publicSite').classList.add('hidden');$('#publicNav').classList.add('hidden');$('.footer').classList.add('hidden');$('#appShell').classList.remove('hidden');buildSidebar();navigate(user.role==='admin'?'dashboard':user.role==='ops'?'ops-home':'client-overview')}

const menus={
 admin:[['dashboard','▦','Dashboard'],['projects','▣','Projects'],['tasks','✓','Tasks'],['team','♟','Team & Access'],['fields','＋','Field Builder'],['proof','⌁','Proof Verification'],['issues','!','Issues'],['vendors','▤','Vendors & Logistics'],['client-control','◉','Client Control'],['chat','✉','Chat'],['reports','▥','Reports'],['settings','⚙','Settings']],
 ops:[['ops-home','⌂','Home'],['ops-tasks','▦','My Tasks'],['ops-update','↻','Update Status'],['ops-proof','▧','Upload Proof'],['ops-issue','!','Report Issue'],['ops-instructions','▣','Instructions'],['ops-chat','✉','Chat'],['ops-contacts','☎','Contacts']],
 client:[['client-overview','⌂','Overview'],['client-progress','▦','Progress'],['client-proof','▧','Verified Proof'],['client-approvals','✓','Approvals'],['client-docs','▤','Documents'],['client-chat','✉','Messages'],['client-reports','▥','Reports'],['client-support','☎','Support']]
};
function buildSidebar(){const role=session.role;$('#sidebar').innerHTML=`<div class="side-brand"><span class="brand-mark">ML</span><span><strong>${role==='admin'?'ADMIN':role==='ops'?'OPS TEAM':'CLIENT'}</strong><small>Marathon LiveOps</small></span></div><nav class="side-nav">${menus[role].map(m=>`<button data-page="${m[0]}"><span class="ico">${m[1]}</span>${m[2]}</button>`).join('')}</nav>`;$$('[data-page]','#sidebar').forEach(b=>b.onclick=()=>navigate(b.dataset.page))}
function navigate(page){session.page=page;$$('[data-page]','#sidebar').forEach(b=>b.classList.toggle('active',b.dataset.page===page));const render=pages[page]||pages.notFound;render()}
function setHead(t,s=''){ $('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s}
function stat(label,val,color='blue'){return `<div class="kpi"><small>${label}</small><strong class="${color}">${val}</strong></div>`}
function deptCards(){return `<div class="dept-grid">${state.departments.map(d=>`<div class="dept-card"><b>${esc(d.name)}</b><strong>${d.progress}%</strong><div class="bar"><i style="width:${d.progress}%"></i></div><span class="status ${statusClass(d.status)}">${d.status}</span></div>`).join('')}</div>`}
function quickBtn(text,action){return `<button class="action-btn" data-action="${action}">${text}</button>`}
function bindQuick(){ $$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='create-task')renderTaskForm();else if(a==='add-team')renderAddTeam();else if(a==='request-update'){state.messages.push({thread:'broadcast',from:'admin',to:'ops',text:'Please submit your latest assigned task status.',time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});save();toast('Update request sent to Ops team.')}else if(a==='broadcast'){const msg=prompt('Broadcast instruction to all Ops members:');if(msg){state.messages.push({thread:'broadcast',from:'admin',to:'ops',text:msg,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});save();toast('Broadcast sent.')}}else if(a==='open-chat')navigate('chat')}) }

const pages={
 dashboard(){setHead('Command Centre',`${state.project.name} • ${state.project.eventDay}`);const completed=state.tasks.filter(t=>t.verified).length,working=state.tasks.filter(t=>/working|started/i.test(t.status)).length,blocked=state.tasks.filter(t=>/blocked|unable/i.test(t.status)).length,pending=state.tasks.filter(t=>t.status==='Finished'&&!t.verified).length;$('#appContent').innerHTML=`<div class="kpi-grid">${stat('PROJECT READY',state.project.readiness+'%')}${stat('VERIFIED',completed,'green')}${stat('WORKING',working,'blue')}${stat('DELAYED',state.issues.length,'amber')}${stat('BLOCKED',blocked,'red')}${stat('PROOF PENDING',pending,'amber')}</div><div class="panel-grid"><div class="panel"><h3>ATTENTION REQUIRED</h3>${state.issues.map(i=>`<div class="attention-row"><span class="status ${statusClass(i.severity)}">${i.severity}</span><b>${esc(i.title)}</b><span>${i.task}</span><span>${i.time}</span></div>`).join('')||'<p>No open issues.</p>'}<div class="attention-row"><span class="status amber">Proof Pending</span><b>Finish Gate Branding</b><span>Venue</span><span>04:08 AM</span></div></div><div class="panel"><h3>QUICK ACTIONS</h3><div class="action-grid">${quickBtn('+ Create Task','create-task')}${quickBtn('+ Add Team','add-team')}${quickBtn('↻ Request Update','request-update')}${quickBtn('▣ Broadcast','broadcast')}${quickBtn('✉ Open Chat','open-chat')}</div></div></div><div class="panel" style="margin-top:16px"><h3>DEPARTMENT READINESS</h3>${deptCards()}</div>`;bindQuick()},
 projects(){setHead('Projects','Project phases, departments and locations.');$('#appContent').innerHTML=`<div class="page-actions"><button class="btn primary" id="newProject">+ Create Project</button><button class="btn ghost" id="editProject">Edit Current Project</button></div><div class="panel"><h3>${esc(state.project.name)}</h3><p>Readiness: <b>${state.project.readiness}%</b> • ${esc(state.project.eventDay)} • Last update ${esc(state.project.lastUpdate)}</p><div class="bar"><i style="width:${state.project.readiness}%"></i></div></div><div class="panel" style="margin-top:16px"><h3>PHASE / DEPARTMENT SETUP</h3>${deptCards()}</div>`;$('#newProject').onclick=()=>toast('Project creation is not enabled in this build yet.');$('#editProject').onclick=()=>{const n=prompt('Project name',state.project.name);if(n){state.project.name=n;save();pages.projects()}}},
 tasks(){setHead('Tasks','Create, configure, assign, escalate and close work.');$('#appContent').innerHTML=`<div class="page-actions"><button class="btn primary" id="createTask">+ Create Task</button><button class="btn ghost" id="exportTasks">Export CSV</button></div><div class="data-table"><div class="data-head"><span>Task</span><span>Priority</span><span>Department</span><span>Assigned</span><span>Status</span><span>Action</span></div>${state.tasks.map(t=>`<div class="data-row"><b>${esc(t.name)}<br><small>${t.id}</small></b><span>${t.priority}</span><span>${t.department}</span><span>${t.assignedTo}</span><span class="status ${statusClass(t.status)}">${t.status}</span><button data-edit-task="${t.id}">Edit</button></div>`).join('')}</div>`;$('#createTask').onclick=renderTaskForm;$('#exportTasks').onclick=exportTasksCSV;$$('[data-edit-task]').forEach(b=>b.onclick=()=>renderTaskForm(b.dataset.editTask))},
 team(){setHead('Team & Access','Control user, role, department, zone and permissions.');$('#appContent').innerHTML=`<div class="page-actions"><button class="btn primary" id="addMember">+ Add Member</button></div><div class="data-table"><div class="data-head"><span>Name</span><span>Role</span><span>Department</span><span>Zone</span><span>Access</span><span>Status</span></div>${state.team.map(x=>`<div class="data-row"><b>${esc(x.name)}</b><span>${esc(x.role)}</span><span>${esc(x.department)}</span><span>${esc(x.zone)}</span><span>${esc(x.access)}</span><span class="status green">${esc(x.status)}</span></div>`).join('')}</div>`;$('#addMember').onclick=renderAddTeam},
 fields(){setHead('Form & Field Control','Admin decides exactly what information Ops must submit.');renderFieldBuilder()},
 proof(){setHead('Proof Verification','Approve, reject or request rework before client visibility.');renderProofs()},
 issues(){setHead('Issues & Blockers','Problems should find Admin automatically.');$('#appContent').innerHTML=`<div class="data-table"><div class="data-head"><span>Issue</span><span>Severity</span><span>Task</span><span>Status</span><span>Time</span><span>Action</span></div>${state.issues.map(i=>`<div class="data-row"><b>${esc(i.title)}</b><span class="status ${statusClass(i.severity)}">${i.severity}</span><span>${i.task}</span><span>${i.status}</span><span>${i.time}</span><button data-resolve="${i.id}">Resolve</button></div>`).join('')}</div>`;$$('[data-resolve]').forEach(b=>b.onclick=()=>{state.issues=state.issues.filter(i=>i.id!==b.dataset.resolve);save();pages.issues();toast('Issue resolved.');})},
 vendors(){setHead('Vendors & Logistics','Vendor, vehicle, driver, material movement and ETA controls.');$('#appContent').innerHTML=`<div class="panel"><h3>LOGISTICS CONTROL FIELDS</h3><div class="form-grid"><div class="form-group"><label>Vendor Name</label><input placeholder="Vendor name"></div><div class="form-group"><label>Vendor POC</label><input placeholder="POC name"></div><div class="form-group"><label>Contact</label><input placeholder="Contact number"></div><div class="form-group"><label>Vehicle No.</label><input placeholder="WB 00 XX 0000"></div><div class="form-group"><label>Driver No.</label><input placeholder="Driver contact"></div><div class="form-group"><label>ETA</label><input type="time"></div><div class="form-group span2"><label>Material / Quantity</label><textarea rows="3"></textarea></div></div><button class="btn primary" id="saveVendor" style="margin-top:14px">Save Logistics Record</button></div>`;$('#saveVendor').onclick=()=>toast('Logistics form UI is ready; persistent vendor records need the vendor data module.')},
 'client-control'(){setHead('Client Control','Choose exactly what the client can see, approve or provide.');const r=state.clientRules;$('#appContent').innerHTML=`<div class="panel-grid"><div class="panel"><h3>VISIBILITY RULES</h3>${[['overall','Overall Project Readiness'],['departments','Department Progress'],['approvedProof','Approved Ground Proof'],['internalRemarks','Internal Remarks'],['vendorContacts','Vendor Contact Details'],['unverifiedIssues','Issues Before Verification']].map(([k,l])=>`<div class="switch-line"><span>${l}</span><button class="switch ${r[k]?'on':''}" data-rule="${k}">${r[k]?'SHOW':'HIDE'}</button></div>`).join('')}</div><div class="panel"><h3>CLIENT ACTION REQUEST</h3><div class="action-grid"><button class="action-btn" data-request="Approve artwork">+ Approve artwork</button><button class="action-btn" data-request="Upload sponsor logo">+ Upload sponsor logo</button><button class="action-btn" data-request="Confirm quantity">+ Confirm quantity</button><button class="action-btn" data-request="Add response">+ Add remark / response</button></div></div></div>`;$$('[data-rule]').forEach(b=>b.onclick=()=>{const k=b.dataset.rule;state.clientRules[k]=!state.clientRules[k];save();pages['client-control']()});$$('[data-request]').forEach(b=>b.onclick=()=>{state.approvals.unshift({id:'AP-'+Date.now(),title:b.dataset.request,type:b.dataset.request,status:'Pending',note:'Requested by Admin.'});save();toast('Client request created.');})},
 chat(){setHead('Project Chat & Help','Task-linked conversations between Admin, Ops and Client.');renderChat('admin')},
 reports(){setHead('Reports & Records','Export client-safe or internal project records.');$('#appContent').innerHTML=`<div class="panel-grid"><div class="panel"><h3>LIVE PROJECT REPORT</h3><p>Generated from the current saved project state.</p><div class="kpi-grid" style="grid-template-columns:repeat(3,1fr)">${stat('READINESS',state.project.readiness+'%')}${stat('TASKS',state.tasks.length)}${stat('ISSUES',state.issues.length,'amber')}</div><div class="page-actions" style="margin-top:18px"><button class="btn primary" id="printReport">Print / Save PDF</button><button class="btn ghost" id="csvReport">Export Tasks CSV</button></div></div><div class="panel"><h3>REPORT INCLUDES</h3><p>✓ Project readiness<br>✓ Department progress<br>✓ Task status<br>✓ Verified milestones<br>✓ Approved proofs<br>✓ Client approvals<br>✓ Decision / chat history</p></div></div>`;$('#printReport').onclick=()=>window.print();$('#csvReport').onclick=exportTasksCSV},
 settings(){setHead('Settings','Project defaults and local recovery controls.');$('#appContent').innerHTML=`<div class="panel"><h3>LOCAL RECOVERY DATA</h3><p>Reset this browser copy back to the approved prototype defaults.</p><button class="btn ghost" id="resetDemo">Reset Local Data</button></div>`;$('#resetDemo').onclick=()=>{if(confirm('Reset all local browser changes?')){state=structuredClone(seed);save();navigate('dashboard');toast('Local data reset.')}}},
 'ops-home'(){setHead('Ops Home',`${session.user.name} • ${session.user.department||''} • ${session.user.zone||''}`);const tasks=state.tasks.filter(t=>t.assignedTo===session.user.id);const urgent=tasks.find(t=>!t.verified&&t.status!=='Finished')||tasks[0];$('#appContent').innerHTML=`<div class="ops-home"><div class="ops-banner"><h2>Good Morning, ${esc(session.user.name)}</h2><p>${esc(state.project.name)} • ${esc(session.user.department||'Operations')} • ${esc(session.user.zone||'Assigned Area')}</p></div><div class="ops-icons">${[['▦','My Tasks','ops-tasks'],['↻','Update','ops-update'],['▧','Proof','ops-proof'],['!','Issue','ops-issue'],['▣','Instructions','ops-instructions'],['✉','Chat','ops-chat']].map(x=>`<button class="ops-icon" data-page="${x[2]}"><b>${x[0]}</b>${x[1]}</button>`).join('')}</div><h4>DO NOW</h4>${urgent?taskCard(urgent,true):'<p>No assigned tasks.</p>'}</div>`;$$('[data-page]','#appContent').forEach(b=>b.onclick=()=>navigate(b.dataset.page));bindTaskButtons()},
 'ops-tasks'(){setHead('My Tasks','Only work assigned to you.');const tasks=state.tasks.filter(t=>t.assignedTo===session.user.id);$('#appContent').innerHTML=`<div class="ops-home"><div class="page-actions"><button class="btn primary" data-filter="open">Do Now</button><button class="btn ghost" data-filter="next">Next</button><button class="btn ghost" data-filter="done">Done</button></div><div id="opsTaskList">${tasks.map(t=>taskCard(t)).join('')}</div></div>`;bindTaskButtons()},
 'ops-update'(){setHead('Update Status','Complete only the fields Admin requested.');const t=getOpsTask();if(!t)return noTask();renderOpsUpdate(t)},
 'ops-proof'(){setHead('Upload Proof','Mandatory evidence before completion.');const t=getOpsTask();if(!t)return noTask();renderOpsProof(t)},
 'ops-issue'(){setHead('Report Issue / Blocker','Send Admin the full context immediately.');const t=getOpsTask();if(!t)return noTask();renderOpsIssue(t)},
 'ops-instructions'(){setHead('Instructions','Project and task instructions from Admin.');const msgs=state.messages.filter(m=>m.to==='ops'&&m.thread==='broadcast');$('#appContent').innerHTML=`<div class="ops-home"><div class="panel"><h3>ADMIN INSTRUCTIONS</h3>${msgs.length?msgs.slice().reverse().map(m=>`<div class="task-card"><b>${esc(m.text)}</b><p>${m.time}</p></div>`).join(''):'<p>No new broadcast instructions.</p>'}</div>${state.tasks.filter(t=>t.assignedTo===session.user.id).map(t=>`<div class="task-card"><span class="status ${statusClass(t.priority)}">${t.priority}</span><h4>${esc(t.name)}</h4><p>${esc(t.instruction||'')}</p></div>`).join('')}</div>`},
 'ops-chat'(){setHead('Need Help / Chat','Task-linked conversation with Admin.');renderChat('ops')},
 'ops-contacts'(){setHead('Important Contacts','Quick operational contacts.');$('#appContent').innerHTML=`<div class="ops-home"><div class="panel"><h3>CONTROL ROOM</h3><p><b>Project Admin</b><br>Use project chat for task support.</p><p><b>Emergency / Medical</b><br>Configured by Admin per event.</p><p><b>Security Control</b><br>Configured by Admin per event.</p></div></div>`},
 'client-overview'(){setHead('Project Overview',`${state.project.name} • Client View`);const verified=state.tasks.filter(t=>t.verified).length;$('#appContent').innerHTML=`<div class="client-hero"><small>OVERALL PROJECT READINESS</small><div class="progress-line"><strong class="blue">${state.project.readiness}%</strong><div class="bar" style="flex:1"><i style="width:${state.project.readiness}%"></i></div><span class="status green">ON TRACK</span></div></div><div class="kpi-grid" style="grid-template-columns:repeat(4,1fr);margin-top:14px">${stat('VERIFIED',verified,'green')}${stat('IN PROGRESS',state.tasks.filter(t=>!t.verified).length)}${stat('MILESTONES','14 / 18')}${stat('CLIENT ACTIONS',state.approvals.filter(a=>a.status==='Pending').length,'amber')}</div><div class="panel-grid"><div class="panel"><h3>WHAT'S HAPPENING NOW</h3>${state.departments.slice(0,4).map(d=>`<div class="switch-line"><span><b>${d.name}</b><br><small>${d.status}</small></span><strong>${d.progress}%</strong></div>`).join('')}</div><div class="panel"><h3>YOUR ACTIONS</h3><div class="client-actions">${state.approvals.filter(a=>a.status==='Pending').slice(0,3).map(a=>`<div class="approval-card"><h4>${esc(a.title)}</h4><p>${esc(a.note)}</p><button class="btn primary" data-page="client-approvals">Open</button></div>`).join('')||'<p>No pending actions.</p>'}</div></div></div>`;$$('[data-page]','#appContent').forEach(b=>b.onclick=()=>navigate(b.dataset.page))},
 'client-progress'(){setHead('Department Progress','Only approved project progress is visible here.');$('#appContent').innerHTML=deptCards()},
 'client-proof'(){setHead('Verified Ground Proof','Only evidence approved by Admin.');const verified=state.tasks.filter(t=>t.verified);$('#appContent').innerHTML=`<div class="proof-grid">${verified.map(t=>proofClientCard(t)).join('')||'<div class="panel"><p>No verified proof yet.</p></div>'}</div>`},
 'client-approvals'(){setHead('Approvals & Information Requests','Respond without leaving the project dashboard.');$('#appContent').innerHTML=`<div class="panel-grid"><div class="panel"><h3>PENDING ACTIONS</h3>${state.approvals.map(a=>`<div class="approval-card"><span class="status ${a.status==='Pending'?'amber':'green'}">${a.status}</span><h4>${esc(a.title)}</h4><p>${esc(a.note)}</p>${a.status==='Pending'?`<div class="task-actions"><button class="verify" data-approve="${a.id}">✓ Approve / Complete</button><button class="rework" data-change="${a.id}">Request Change</button></div>`:''}</div>`).join('')}</div><div class="panel"><h3>CLIENT → ADMIN → OPS</h3><p>Your response is recorded in the project and can be routed by Admin to the relevant operations team.</p></div></div>`;$$('[data-approve]').forEach(b=>b.onclick=()=>{const a=state.approvals.find(x=>x.id===b.dataset.approve);a.status='Approved';save();pages['client-approvals']();toast('Response submitted to Admin.');});$$('[data-change]').forEach(b=>b.onclick=()=>{const a=state.approvals.find(x=>x.id===b.dataset.change);const m=prompt('What change is required?');if(m){a.status='Change Requested';state.messages.push({thread:'client-artwork',from:'client',to:'admin',text:m,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});save();pages['client-approvals']();toast('Change request sent.')}})},
 'client-docs'(){setHead('Documents','Approved project documents.');$('#appContent').innerHTML=`<div class="panel"><h3>DOCUMENT CENTRE</h3><div class="task-card"><b>Project Execution Summary</b><p>Client-safe project summary • Demo record</p><button class="btn ghost" onclick="window.print()">Print / Save PDF</button></div><div class="task-card"><b>Approved Artwork Pack</b><p>Production-ready approved artwork • Demo record</p></div></div>`},
 'client-chat'(){setHead('Client ↔ Admin Messages','One controlled project conversation.');renderChat('client')},
 'client-reports'(){setHead('Client Reports','A clean project record built from verified live updates.');$('#appContent').innerHTML=`<div class="panel-grid"><div class="panel"><h3>EXECUTIVE SUMMARY</h3><div class="switch-line"><span>Overall Readiness</span><b>${state.project.readiness}%</b></div><div class="switch-line"><span>Verified Milestones</span><b>${state.tasks.filter(t=>t.verified).length}</b></div><div class="switch-line"><span>Open Client Actions</span><b>${state.approvals.filter(a=>a.status==='Pending').length}</b></div><div class="switch-line"><span>Latest Update</span><b>${state.project.lastUpdate}</b></div><button class="btn primary" id="clientPrint" style="margin-top:14px">Print / Save PDF</button></div><div class="panel"><h3>CLIENT-SAFE INFORMATION ONLY</h3><p>Internal remarks, vendor disputes, private contacts and unverified issues remain hidden unless Admin explicitly changes visibility.</p></div></div>`;$('#clientPrint').onclick=()=>window.print()},
 'client-support'(){setHead('Support','Contact the project Admin.');$('#appContent').innerHTML=`<div class="panel"><h3>PROJECT SUPPORT</h3><p>Use <b>Messages</b> for project questions and approval discussions.</p><button class="btn primary" id="supportChat">Open Messages</button></div>`;$('#supportChat').onclick=()=>navigate('client-chat')},
 notFound(){setHead('Page');$('#appContent').innerHTML='<div class="panel">Page not found.</div>'}
};

function taskCard(t,urgent=false){return `<div class="task-card"><span class="status ${statusClass(urgent?'Critical':t.priority)}">${urgent?'URGENT':t.priority}</span><h4>${esc(t.name)}</h4><div class="task-meta"><span>${t.id}</span><span>${esc(t.zone)}</span><span>Deadline ${esc(t.deadline)}</span></div><div class="bar"><i style="width:${t.progress}%"></i></div><div class="task-actions"><button class="btn primary" data-task-open="${t.id}">${t.status==='Not Started'?'START / OPEN':'OPEN TASK'}</button>${!t.verified?`<button class="btn ghost" data-task-help="${t.id}">NEED HELP</button>`:''}</div></div>`}
function bindTaskButtons(){ $$('[data-task-open]').forEach(b=>b.onclick=()=>{session.selectedTask=b.dataset.taskOpen;navigate('ops-update')});$$('[data-task-help]').forEach(b=>b.onclick=()=>{session.selectedTask=b.dataset.taskHelp;navigate('ops-chat')}) }
function getOpsTask(){return state.tasks.find(t=>t.id===session.selectedTask)||state.tasks.find(t=>t.assignedTo===session.user.id&&!t.verified)||state.tasks.find(t=>t.assignedTo===session.user.id)}
function noTask(){$('#appContent').innerHTML='<div class="panel"><p>No assigned task selected.</p></div>'}
function renderOpsUpdate(t){session.selectedTask=t.id;const fields=t.fields.length?t.fields:seed.tasks[0].fields;$('#appContent').innerHTML=`<div class="ops-home"><div class="task-card"><span class="status ${statusClass(t.priority)}">${t.priority}</span><h4>${esc(t.name)}</h4><p>${esc(t.instruction||'')}</p><div class="task-meta"><span>${t.id}</span><span>${esc(t.zone)}</span><span>${esc(t.deadline)}</span></div></div><form class="panel" id="opsUpdateForm"><h3>ADMIN-REQUIRED INFORMATION</h3>${fields.map((f,i)=>opsField(f,i,t)).join('')}<button class="btn primary full" type="submit">Save Update</button></form><div class="page-actions" style="margin-top:10px"><button class="btn ghost" id="goProof">Next: Upload Proof</button><button class="btn ghost" id="goIssue">Report Issue</button></div></div>`;$('#opsUpdateForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);const status=fd.get('field-0')||t.status;const prog=Number(fd.get('field-1')||t.progress);t.status=status;t.progress=Math.max(0,Math.min(100,prog));t.remark=fd.get('field-4')||t.remark;const issue=fd.get('field-3');if(issue&&issue!=='No')t.issue=issue;save();toast('Task update saved.');};$('#goProof').onclick=()=>navigate('ops-proof');$('#goIssue').onclick=()=>navigate('ops-issue')}
function opsField(f,i,t){let val='';if(i===0)val=t.status;if(i===1)val=t.progress;if(i===4)val=t.remark;const req=f.required?'required':'';if(f.type==='dropdown')return `<div class="form-group"><label>${esc(f.label)}${f.required?' *':''}</label><select name="field-${i}" ${req}>${(f.options||[]).map(o=>`<option ${o==val?'selected':''}>${esc(o)}</option>`).join('')}</select></div>`;if(f.type==='remark')return `<div class="form-group"><label>${esc(f.label)}${f.required?' *':''}</label><textarea name="field-${i}" rows="3" ${req}>${esc(val)}</textarea></div>`;return `<div class="form-group"><label>${esc(f.label)}${f.required?' *':''}</label><input name="field-${i}" type="${f.type==='number'?'number':'text'}" value="${esc(val)}" ${req}></div>`}
function renderOpsProof(t){session.selectedTask=t.id;$('#appContent').innerHTML=`<div class="ops-home"><div class="panel"><h3>${esc(t.name)}</h3><p>Minimum ${t.proofMin} photo(s) required by Admin.</p><div class="upload-grid" id="proofTiles">${[...Array(Math.max(t.proofMin,3))].map((_,i)=>proofTile(t,i)).join('')}</div><input class="hidden" type="file" id="proofInput" accept="image/*" capture="environment"><div style="margin-top:14px"><span class="status ${t.proofs.length>=t.proofMin?'green':'amber'}">${t.proofs.length} / ${t.proofMin} UPLOADED</span></div><button class="btn primary full" id="submitProof" style="margin-top:14px" ${t.proofs.length<t.proofMin?'disabled':''}>Submit for Admin Verification</button></div></div>`;let targetIndex=0;$$('[data-proof-slot]').forEach(b=>b.onclick=()=>{targetIndex=Number(b.dataset.proofSlot);$('#proofInput').click()});$('#proofInput').onchange=async e=>{
  const file=e.target.files[0];if(!file)return;
  try{
    const localData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
    let data=localData, syncPending=false;
    if(window.LiveOpsCloud?.isConfigured()){
      if(navigator.onLine){
        try{toast('Uploading proof…');const uploaded=await window.LiveOpsCloud.uploadProof(t.id,file);data=uploaded.url;}
        catch(uploadErr){console.warn(uploadErr);syncPending=true;await window.LiveOpsResilience?.queueProof(t.id,file,localData);}
      }else{syncPending=true;await window.LiveOpsResilience?.queueProof(t.id,file,localData);}
    }
    t.proofs[targetIndex]={name:file.name,data,localData,syncPending,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})};
    save();renderOpsProof(t);toast('Photo added.');
  }catch(err){console.error(err);toast('Photo upload failed.');}
};$('#submitProof').onclick=()=>{if(t.proofs.length<t.proofMin)return toast(`Upload at least ${t.proofMin} photos.`);t.status='Finished';t.progress=100;t.verified=false;save();toast('Submitted for Admin verification.');navigate('ops-tasks')}}
function proofTile(t,i){const p=t.proofs[i];return `<button class="upload-tile" data-proof-slot="${i}">${p?`<img src="${p.data}" alt="Proof ${i+1}">${p.syncPending?'<em class="proof-sync">Queued</em>':''}`:`<span>＋<br>Photo ${i+1}</span>`}</button>`}
function renderOpsIssue(t){$('#appContent').innerHTML=`<div class="ops-home"><form class="panel" id="issueForm"><h3>${esc(t.name)}</h3><div class="form-group"><label>Issue Type</label><select name="type"><option>Material Not Reached</option><option>Manpower Shortage</option><option>Vehicle Delay</option><option>Permission Issue</option><option>Safety Issue</option><option>Other</option></select></div><div class="form-group"><label>Severity</label><select name="severity"><option>High</option><option>Medium</option><option>Low</option><option>Critical</option></select></div><div class="form-group"><label>Remark</label><textarea required name="remark" rows="4"></textarea></div><button class="btn primary full" type="submit" style="background:var(--red)">Send to Admin</button></form></div>`;$('#issueForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);state.issues.unshift({id:'IS-'+Date.now(),task:t.id,title:f.get('remark'),severity:f.get('severity'),status:'Open',time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});t.issue=f.get('type');if(/critical|high/i.test(f.get('severity')))t.status='Blocked';save();toast('Issue sent to Admin.');navigate('ops-home')}}
function renderTaskForm(id){const t=id?state.tasks.find(x=>x.id===id):null;setHead(t?'Edit Task':'Create / Configure Task','Admin decides what Ops must do, submit and prove.');$('#appContent').innerHTML=`<div class="panel-grid"><form class="panel" id="taskForm"><h3>${t?'EDIT TASK':'NEW TASK'}</h3><div class="form-grid"><div class="form-group span2"><label>Task Name</label><input required name="name" value="${esc(t?.name||'')}"></div><div class="form-group"><label>Phase</label><select name="phase"><option>Expo</option><option>Venue</option><option>Race Course</option><option>Dismantling</option></select></div><div class="form-group"><label>Department</label><select name="department">${state.departments.map(d=>`<option ${d.name===t?.department?'selected':''}>${d.name}</option>`).join('')}</select></div><div class="form-group"><label>Zone / Location</label><input name="zone" value="${esc(t?.zone||'')}"></div><div class="form-group"><label>Assigned To</label><select name="assignedTo">${state.users.filter(u=>u.role==='ops').map(u=>`<option value="${u.id}" ${u.id===t?.assignedTo?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><div class="form-group"><label>Priority</label><select name="priority"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><div class="form-group"><label>Deadline</label><input name="deadline" type="time"></div><div class="form-group"><label>Minimum Photos</label><input name="proofMin" type="number" min="0" value="${t?.proofMin??3}"></div><div class="form-group"><label>Client Visibility</label><select name="clientVisibility"><option>Hidden</option><option>Status Only</option><option>Status + Approved Proof</option><option>Full Update</option></select></div><div class="form-group span2"><label>Instruction</label><textarea name="instruction" rows="3">${esc(t?.instruction||'')}</textarea></div></div><button class="btn primary" type="submit" style="margin-top:14px">Save & Assign</button></form><div class="panel"><h3>TASK RULES</h3>${['Proof mandatory','Admin verification','Ops can edit','Escalate if overdue','Allow reopen'].map(x=>`<div class="switch-line"><span>${x}</span><span class="switch on">ON</span></div>`).join('')}<p style="margin-top:18px"><b>Completion Flow</b><br><br>ASSIGN → EXECUTE → PROVE → VERIFY → CLOSE</p></div></div>`;$('#taskForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));if(t){Object.assign(t,f,{proofMin:Number(f.proofMin)});}else{state.tasks.unshift({id:'TS-'+Date.now().toString().slice(-5),...f,proofMin:Number(f.proofMin),status:'Not Started',progress:0,verification:true,proofs:[],remark:'',issue:'',verified:false,fields:structuredClone(seed.tasks[0].fields)})}save();toast('Task saved and assigned.');navigate('tasks')}}
function renderAddTeam(){setHead('Add Team Member','Create access and assign role / department / zone.');$('#appContent').innerHTML=`<form class="panel" id="teamForm"><div class="form-grid"><div class="form-group"><label>Name</label><input required name="name"></div><div class="form-group"><label>User ID</label><input required name="userId"></div><div class="form-group"><label>Password</label><input required name="password" value="welcome123"></div><div class="form-group"><label>Role</label><select name="role"><option>Supervisor</option><option>Coordinator</option><option>Lead</option><option>Verifier</option></select></div><div class="form-group"><label>Department</label><select name="department">${state.departments.map(d=>`<option>${d.name}</option>`).join('')}</select></div><div class="form-group"><label>Zone</label><input name="zone" value="Assigned Area"></div><div class="form-group"><label>Access</label><select name="access"><option>Assigned Only</option><option>Department</option><option>Proof Only</option></select></div></div><button class="btn primary" type="submit" style="margin-top:14px">Create Ops Access</button></form>`;$('#teamForm').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));state.team.push({...f,status:'Active'});state.users.push({id:f.userId,password:f.password,role:'ops',name:f.name,department:f.department,zone:f.zone});save();toast('Team member access created.');navigate('team')}}
let builderFields=structuredClone(seed.tasks[0].fields);
function renderFieldBuilder(){ $('#appContent').innerHTML=`<div class="field-builder"><div class="panel"><h3>ADD FIELD</h3><div class="field-palette">${[['text','T  Text'],['number','123  Number'],['dropdown','⌄  Dropdown'],['multiselect','☑  Multi-select'],['yesno','◉  Yes / No'],['datetime','◷  Date & Time'],['location','⌖  Location'],['photo','▧  Photo'],['video','▶  Video'],['file','▤  File'],['remark','≡  Remark']].map(x=>`<button data-add-field="${x[0]}">${x[1]}</button>`).join('')}</div></div><div class="panel"><h3>REQUIRED INFORMATION TEMPLATE</h3><div class="field-list">${builderFields.map((f,i)=>fieldRow(f,i)).join('')}</div><div class="page-actions" style="margin-top:14px"><button class="btn primary" id="saveTemplate">Save Template</button><button class="btn ghost" id="applyTemplate">Apply to Selected Ops Task</button></div></div></div>`;$$('[data-add-field]').forEach(b=>b.onclick=()=>{builderFields.push({label:'New Field',type:b.dataset.addField,required:false,opsEdit:true,client:'No',options:b.dataset.addField==='dropdown'?['Option 1','Option 2']:[]});renderFieldBuilder()});$$('[data-field-index]').forEach(r=>{const i=Number(r.dataset.fieldIndex);r.querySelector('[name=label]').oninput=e=>builderFields[i].label=e.target.value;r.querySelector('[name=required]').onchange=e=>builderFields[i].required=e.target.value==='Yes';r.querySelector('[name=opsEdit]').onchange=e=>builderFields[i].opsEdit=e.target.value==='Yes';r.querySelector('[name=client]').onchange=e=>builderFields[i].client=e.target.value;r.querySelector('[data-remove-field]').onclick=()=>{builderFields.splice(i,1);renderFieldBuilder()}});$('#saveTemplate').onclick=()=>{localStorage.setItem(STORE+'-template',JSON.stringify(builderFields));toast('Field template saved.');};$('#applyTemplate').onclick=()=>{const id=prompt('Enter Task ID to apply this template (example RC-118):','RC-118');const t=state.tasks.find(x=>x.id===id);if(!t)return toast('Task not found.');t.fields=structuredClone(builderFields);save();toast('Field template applied to '+id);}}
function fieldRow(f,i){return `<div class="field-row" data-field-index="${i}"><input name="label" value="${esc(f.label)}"><span>${esc(f.type)}</span><select name="required"><option ${f.required?'selected':''}>Yes</option><option ${!f.required?'selected':''}>No</option></select><select name="opsEdit"><option ${f.opsEdit?'selected':''}>Yes</option><option ${!f.opsEdit?'selected':''}>No</option></select><select name="client"><option>${esc(f.client||'No')}</option><option>No</option><option>Yes</option><option>Status</option><option>Approved</option></select><button data-remove-field>×</button></div>`}
function renderProofs(){const pending=state.tasks.filter(t=>t.status==='Finished'&&!t.verified);$('#appContent').innerHTML=`<div class="proof-grid">${pending.map(t=>proofAdminCard(t)).join('')||'<div class="panel"><p>No proof awaiting verification.</p></div>'}</div>`;$$('[data-verify]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.verify);t.verified=true;save();renderProofs();toast('Task verified. Client visibility updated.');});$$('[data-rework]').forEach(b=>b.onclick=()=>{const t=state.tasks.find(x=>x.id===b.dataset.rework);const reason=prompt('Rework reason:','Please upload clearer proof and recheck alignment.');if(reason){t.status='Working';t.verified=false;state.messages.push({thread:t.id,from:'admin',to:'ops',text:'Rework required: '+reason,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});save();renderProofs();toast('Rework sent to Ops.')}})}
function proofAdminCard(t){const p=t.proofs[0]?.data;return `<div class="proof-card"><div class="proof-photo" style="${p?`background-image:url('${p}')`:''}">${p?'':'VERIFIED PHOTO / PROOF'}</div><div class="proof-body"><span class="status amber">PENDING VERIFICATION</span><h4>${esc(t.name)}</h4><p>${t.id} • ${esc(t.department)} • ${t.proofs.length} proof(s)<br>${esc(t.remark||'No remark')}</p><div class="proof-actions"><button class="verify" data-verify="${t.id}">✓ VERIFY</button><button class="rework" data-rework="${t.id}">↻ REWORK</button></div></div></div>`}
function proofClientCard(t){const p=t.proofs[0]?.data;return `<div class="proof-card"><div class="proof-photo" style="${p?`background-image:url('${p}')`:''}">${p?'':'VERIFIED GROUND PROOF'}</div><div class="proof-body"><span class="status green">✓ VERIFIED</span><h4>${esc(t.name)}</h4><p>${esc(t.department)} • ${esc(t.zone)}</p></div></div>`}
function renderChat(viewer){const allowed=viewer==='client'?state.messages.filter(m=>m.from==='client'||m.to==='client'):viewer==='ops'?state.messages.filter(m=>m.from==='ops'||m.to==='ops'):state.messages;const threads=[...new Set(allowed.map(m=>m.thread))];const selected=session.chatThread||threads[0]||(viewer==='client'?'client-artwork':'RC-118');session.chatThread=selected;const messages=allowed.filter(m=>m.thread===selected);$('#appContent').innerHTML=`<div class="chat-layout"><div class="thread-list">${threads.map(t=>`<div class="thread ${t===selected?'active':''}" data-thread="${t}"><b>${esc(t)}</b><small>${allowed.filter(m=>m.thread===t).slice(-1)[0]?.text||''}</small></div>`).join('')}</div><div class="chat-box"><div class="messages">${messages.map(m=>`<div class="bubble ${m.from===viewer?'me':''}">${esc(m.text)}<small>${m.from.toUpperCase()} • ${m.time}</small></div>`).join('')}</div><form class="chat-compose" id="chatForm"><input required placeholder="Type a message…"><button class="btn primary">Send</button></form></div></div>`;$$('[data-thread]').forEach(x=>x.onclick=()=>{session.chatThread=x.dataset.thread;renderChat(viewer)});$('#chatForm').onsubmit=e=>{e.preventDefault();const input=e.target.querySelector('input'),text=input.value.trim();if(!text)return;const to=viewer==='admin'?(selected.startsWith('client')?'client':'ops'):'admin';state.messages.push({thread:selected,from:viewer,to,text,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})});save();renderChat(viewer)}}
function exportTasksCSV(){const rows=[['ID','Task','Department','Zone','Priority','Status','Progress','Deadline','Verified'],...state.tasks.map(t=>[t.id,t.name,t.department,t.zone,t.priority,t.status,t.progress,t.deadline,t.verified])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='marathon-liveops-tasks.csv';a.click();URL.revokeObjectURL(url);toast('CSV exported.')}

// Production-mode indicator: never disguise demo/local mode as a connected live backend.
if(!window.LiveOpsCloud?.isConfigured()){
  const lp=document.querySelector('.live-pill');
  if(lp){lp.textContent='● DEMO MODE';lp.style.background='#fff4d6';lp.style.color='#8a5a00';}
}


// V4 connectivity + offline queue UI
(function(){
  const host=document.querySelector('.header-actions');
  if(host){const badge=document.createElement('span');badge.id='syncBadge';badge.className='sync-badge';host.prepend(badge);}
  function updateSync(e){const d=e?.detail||{online:navigator.onLine,pending:0,syncing:false};const b=document.getElementById('syncBadge');if(!b)return;b.className='sync-badge '+(!d.online?'offline':d.pending?'pending':'online');b.textContent=!d.online?`OFFLINE • ${d.pending||0} QUEUED`:d.syncing?'SYNCING…':d.pending?`${d.pending} QUEUED`:'SYNCED';}
  window.addEventListener('liveops-sync-status',updateSync);updateSync();
  window.addEventListener('liveops-proof-synced',e=>{const {taskId,localData,remoteUrl}=e.detail||{};const t=state.tasks.find(x=>x.id===taskId);if(!t||!remoteUrl)return;const p=t.proofs.find(x=>x.localData===localData);if(p){p.data=remoteUrl;p.syncPending=false;localStorage.setItem(STORE,JSON.stringify(state));window.LiveOpsResilience?.safeSave(state,session.role);if(session.page==='ops-proof')renderOpsProof(t);toast('Queued proof synced.');}});
})();
